---
title: "Project Work"
author: "SakaiAtMidnight"
date: "November 4, 2014"
output: pdf_document
---

We load the data:
```{r}
library(glmnet)
library(stringr)
library(plyr)


#read in detailed results of the tournament
detailedT = read.csv("tourney_detailed_results.csv")
#read in regular seasons detailed results
detailedR = read.csv("regular_season_detailed_results.csv")
#read in seeds data
seeds = read.csv("tourney_seeds.csv")
```


Subset 2014 info:
```{r}
#select 2014 regular season data
regSeason2014D = detailedR[which(detailedR$season == 2014),]
#extract 2014 tournament season data
tourney2014D = detailedT[which(detailedT$season == 2014),]
#extract 2014 tournament seeds data
seeds2014 = seeds[which(seeds$season == 2014),]
```
Including Seeds:
```{r}
tourney2014D = cbind(cbind(tourney2014D, rep(0, dim(tourney2014D)[1])),
                     rep(0, dim(tourney2014D)[1]))

colnames(tourney2014D)[35:36] = c("wSeed", "lSeed")
#reorganize the columns to include "wSeed" and "lSeed"
tourney2014D = tourney2014D[, c(1:2, 35, 3:4, 36, 5:34)]

#extract seeds numbers and store them into tournament data
for(i in 1:dim(tourney2014D)[1]){
  tourney2014D[i, "wSeed"] = as.character(seeds2014[which(seeds2014$team == tourney2014D$wteam[i]),"seed"])
  tourney2014D[i, "lSeed"] = as.character(seeds2014[which(seeds2014$team == tourney2014D$lteam[i]),"seed"])
}
```

Subsetting Tournament into Rounds:
```{r}
#subset first four tournament teams 
firstFour = tourney2014D[1:4,]
#extract first four winners
firstFourWinners = firstFour[,c("wSeed", "wteam")]

#subset first round data
firstRound = tourney2014D[5:36,]
#extract first round winners
firstRoundWinners = firstRound[,c("wSeed", "wteam")]

#subset second round data
secondRound = tourney2014D[37:52,]
#extract second round winners
secondRoundWinners = secondRound[,c("wSeed", "wteam")]

#subset sweet sixteen data
sweetSixteen = tourney2014D[53:60,]
#extract sweet sixteen winning teams
sweetSixteenWinners = sweetSixteen[,c("wSeed", "wteam")]

#subset elite eight data
eliteEight = tourney2014D[61:64,]
#extract elite eight winning teams
eliteEightWinners = eliteEight[,c("wSeed", "wteam")]

#subset final four data
finalFour = tourney2014D[65:67,]
#extract final four teams
finalFourWinners = finalFour[,c("wSeed", "wteam")]
```
```{r}
#replace 'w' and 'l' with 'a' and 'b'
ChangeName <- function(df){
  names(df) <- str_replace_all(names(df), '^w', 'a.')
  names(df) <- str_replace_all(names(df), '^l', 'b.')
  return(df)
}
regSeason2014D <- ChangeName(regSeason2014D)
```
Rename the columns
```{r}
format <- function(df){
#write a function named exchange which takes:
#input: data
#output: exchange team a and team b by a larger team ID
#exchange corresponding results of team a and team b after team ID is changed
exchange <- function(data){
  result <- 0
  #data <- cbind(data, result)
  for(i in 1: nrow(data)){
    if (data$a.team[i] > data$b.team[i]){
      result[i] <- 0
      #store a.team ID as temp
      temp <- data$a.team[i]
      #assign b.team ID as a.team ID
      data$a.team[i] <- data$b.team[i]
      #reassign b.team ID with temp
      data$b.team[i] <- temp
      #store team a's data as temp.vec
      temp.vec <- data[i, 9:21]
      #exchange team a's data with team b's
      data[i, 9:21] <- data[i, 22:34]
      data[i, 22:34] <- temp.vec
    }
    else{
      result[i] <-1
    }
  }
  return(cbind(data, result))
}
  datanew <- exchange(df)
  #delete columns with unnecessary information
datanew = datanew[, -c(1,2,3,5,7)]
#normalize data 
datanewS = as.data.frame(scale(datanew))
datanewS = datanewS[, -30]
#add the response column (binary number)
datanewS = cbind(datanewS, datanew$result)
#store datanewS as a matrix
datanewS = as.matrix(datanewS)
return(datanewS)
}

datanewS <- format(regSeason2014D)



#apply exchange function to 2014 regular seasons results

library(stringr)

#write an function named average which takes:
#input: data, index1 (first team ID) and index2 (second team ID)
#output: average seasonal results of team a and team b 
average <- function(data, index1, index2){
  data$season <- NULL
  data$daynum <- NULL
  data$a.loc <- NULL
  team.a <- str_detect(names(data),'^a') | str_detect(names(data),'numot')
  team.b <- str_detect(names(data),'^b') | str_detect(names(data),'numot')
  
  index1.a <- data[str_detect(data$a.team, index1), team.a]
  index1.b <- data[str_detect(data$b.team, index1), team.b]
 #average out relevant data of first team using apply() 
  index1.mean <- (apply(index1.a,2,sum)+apply(index1.b,2,sum))/(nrow(index1.a)+nrow(index1.b))
  #remove the first row of team ID
  index1.mean <- index1.mean[-1]
  index2.a <- data[str_detect(data$a.team, index2), team.a]
  index2.b <- data[str_detect(data$a.team, index2), team.b]
 #average out relevant data of second team using apply()
  index2.mean <- (apply(index2.a,2,sum)+apply(index2.b,2,sum))/(nrow(index2.a)+nrow(index2.b))
  #remove the first row of team ID
  index2.mean <- index2.mean[-1]
  
  data$a.team <- NULL
  data$b.team <- NULL
  #return an output of average statistics of two teams
  output <- c(index1.mean[1],index2.mean[1],mean(index1.mean[2],index1.mean[2]), index1.mean[-(1:2)],index2.mean[-(1:2)])
  
  
  names(output) <- names(data)
  return(as.matrix(output))
}



# run LASSO regression with cross validation
# alpha = 1
lm1 = cv.glmnet(datanewS[,1:29], datanewS[,30], standardize=FALSE, 
                               family = "binomial",alpha = 1, 
                type.measure = "auc") 

#predict 2014 tournament results 
outcome1 <- rep(NA,nrow(tourney2014D))
for (i in 1:nrow(tourney2014D)){
#apply function `average` on 2014 tournament teams
#to get average regular seasons data 
  game <-average(regSeason2014D,as.character(tourney2014D[i,'wteam']),as.character(tourney2014D[i,'lteam']))
#predict tournament results using predict() 
  outcome1[i] <- predict(lm1,t(game),type='response')
}
#calculate probability that the model gives correct prediction
sum(outcome1 >=0.5)/67

# run ELASTIC regression with cross validation
# alpha=0.5
lm2 = cv.glmnet(datanewS[,1:29], datanewS[,30], standardize=FALSE, 
                family = "binomial",alpha = 0.5,
                type.measure = "auc") 

outcome2 <- rep(NA,nrow(tourney2014D))
for (i in 1:nrow(tourney2014D)){
#apply function `average` on 2014 tournament teams 
#to get average regular seasons data    
  game <-average(regSeason2014D,as.character(tourney2014D[i,'wteam']),as.character(tourney2014D[i,'lteam']))
 #predict tournament results using predict()

  outcome2[i] <- predict(lm2,t(game),type='response')
}
#calculate probability that the model gives correct prediction
sum(outcome2 >=0.5)/67

#run RIDGE regression with cross validation
lm3 = cv.glmnet(datanewS[,1:29], datanewS[,30], standardize=FALSE, 
                family = "binomial",alpha = 0) 

outcome3 <- rep(NA,nrow(tourney2014D))
for (i in 1:nrow(tourney2014D)){
#apply function `average` on 2014 tournament teams 
#to get average regular seasons data 
 game <-average(regSeason2014D,as.character(tourney2014D[i,'wteam']),as.character(tourney2014D[i,'lteam']))
 #predict tournament results using predict()

  outcome3[i] <- predict(lm3,t(game),type='response')
}

#calculate probability that the model gives correct prediction
sum(outcome3 >=0.5)/67

library(arm)
#run Bayesian generalized linear models
fit.bayes <- bayesglm(datanewS[,30]~.,data=as.data.frame(datanewS[,1:29]), family = 'binomial')
# use stepwise to choose covariates
lm4 <- suppressWarnings(step(fit.bayes,scope=list(upper=~.,lower=~1), direction="both",trace=FALSE))

outcome4 <- rep(NA,nrow(tourney2014D))
for (i in 1:nrow(tourney2014D)){
  game <-average(regSeason2014D,as.character(tourney2014D[i,'wteam']),as.character(tourney2014D[i,'lteam']))
  outcome4[i] <- predict(fit.bayes,as.data.frame(t(game)),type='response')
}
sum(outcome4 >=0.5)/67

```


```{r}
###First round result
library(stringr)
#set the seed in the order
seed <- paste0(rep(c("W","X","Y","Z"), each = 16),
               c("01",16,"08","09","05",12,"04",13,"06",11,"03",14,"07",10,"02",15))
seed.four <- firstFour$wSeed
seed[which(seed == "X16")]=seed.four[1]
seed[which(seed == "Y12")]=seed.four[2]
seed[which(seed == "Y16")]=seed.four[3]
seed[which(seed == "Y11")]=seed.four[4]
firstround <- NULL
for (i in 1:length(seed)){
  if(seed[i] %in% firstRound$wSeed){
    firstround <- c(firstround,firstRound[which(firstRound$wSeed == seed[i]),]$wteam)
  }
  else if(seed[i]  %in% firstRound$lSeed){
    firstround <- c(firstround,firstRound[which(firstRound$lSeed == seed[i]),]$lteam)
  }
}
regSeason2014 <- ChangeName(regSeason2014D)
#input: firstround teamid, regular season data, seed order, model
firstround.winners <- function(firstround, data,seed,model){
  id <- matrix(firstround,ncol = 2, byrow = TRUE)
  seed <- matrix(seed, ncol = 2, byrow = TRUE)
  win <- 0; game <- 0
  seedWinner <- 0
  for(i in 1:nrow(id)){
    game <- average(data, id[i,1],id[i,2])
    game=t(game)
    if (class(model)[1]=="bayesglm"){
        game=as.data.frame(game)
        win[i] <- predict(model, game, type = "response")
        }else{
    win[i] <- predict(model, game, type = "response")}
    if(win[i] >= 0.5){
      win[i] <- id[i,1]
      seedWinner[i] <- seed[i,1]
    }else{
      win[i] <- id[i,2]
      seedWinner[i] <- seed[i,2]
    }
        
  }
  winner <- data.frame(Wseed=seedWinner[1:8],Wwinner=win[1:8],Xseed=seedWinner[9:16],
                       Xwinner=win[9:16],Yseed=seedWinner[17:24],Ywinner=win[17:24],
                       Zseed=seedWinner[25:32],Zwinner=win[25:32])
  return(winner)
}
#predict firstround of 2014 tournament competition with model lasso
firstround.winners(as.character(firstround), regSeason2014D,seed,lm1)
#predict firstround of 2014 tournament competition with model Elastic
firstround.winners(as.character(firstround), regSeason2014D,seed,lm2)
#predict firstround of 2014 tournament competition with model ridge regression
firstround.winners(as.character(firstround), regSeason2014D,seed,lm3)
#predict firstround of 2014 tournament competition with Bayesian GLM with stepwise
firstround.winners(as.character(firstround), regSeason2014D,seed,lm4)

```


